- name: show return value of command module
  hosts: pi-server
  tasks:
    - name: capture output of id command
      command: id -un
      register: login
    - debug: var=login
    - debug: msg="Logged in as user {{ login.stdout }}"

    - name: Run myprog
      command: /opt/myprog
      register: result
      ignore_errors: True
    - debug: var=result
